---
- name: Create a working directory
  ansible.builtin.file:
    path:  "/var/local/{{ role_name }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: Copy Monitoring config files
  ansible.builtin.copy:
   src: ../files/fullnode
   dest: "/opt/{{ role_name }}/"
   owner: "{{ ansible_user }}"
   group: "{{ ansible_user }}"

- name: Create and start Penumbra Fullnode
  docker_compose:
    project_src:  /opt/{{ role_name }}/fullnode/
    files:
    - docker-compose.yml
  become: true