---
- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true
  become: true
- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 1800 # One hour
  become: true